add-debug-boot
add new debug boot mode which does not load a saved overlay, and uses a tempfs for userdata, while bind mounting an existing roms, saves, bios for easier testing.

diff --git a/package/boot/knulli-initramfs/init b/package/boot/knulli-initramfs/init
--- a/package/boot/knulli-initramfs/init
+++ b/package/boot/knulli-initramfs/init
@@ -78,15 +78,19 @@ do_root() {
     mount -t tmpfs -o size=256M tmpfs /overlay_root || return 1
     mkdir /overlay_root/base /overlay_root/overlay /overlay_root/work /overlay_root/saved || return 1
 
-    # fill the overlay with the stored one
-    if test -f /boot_root/boot/overlay
+    # Keep the active boot mode outside the overlay contents we save.
+    if test -f /boot_root/boot/bootmode.debug
     then
-	# the mount can fail if the fs was open in write and not correctly closed
-	if mount -o ro /boot_root/boot/overlay /overlay_root/saved
-	then
-	    cp -pr /overlay_root/saved/* /overlay_root/overlay || return 1
-	    umount /overlay_root/saved                         || return 1
-	fi
+        touch /overlay_root/bootmode.debug || return 1
+        echo "[DEBUG BOOT] Skipping saved overlay restore"
+    elif test -f /boot_root/boot/overlay
+    then
+        # the mount can fail if the fs was open in write and not correctly closed
+        if mount -o ro /boot_root/boot/overlay /overlay_root/saved
+        then
+            cp -pr /overlay_root/saved/* /overlay_root/overlay || return 1
+            umount /overlay_root/saved                         || return 1
+        fi
     fi
 
     # mount the squashfs
